spring:
  boot:
    admin:
      client:
        # admin server 주소
        url: http://localhost:8080
        # 애플리케이션 로딩이 완료된 후 자동으로 Admin Server 에 등록
        auto-registration: true
        username: client
        password: client
        instance:
          name: foobar-client-2-8082
          # 현재 admin-client 자기 자신의 주소
          service-url: http://localhost:8081
#          health-url: http://localhost:8081/actuator/health
#          management-url: http://localhost:8081/actuator
          metadata:
            user:
              name: client
              password: client